spring:
  application:
    name: storage-service
server:
  port: 8108
  hostname: localhost
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
    default-model-expand-depth: 3
    persist-authorization: true
static:
  folder:
    path: ${DEFAULT_STATIC_PATH}
